feat: Corestore.from(store)
holepunchto/corestore pull request #31
Opened 2022-09-01 06:46 UTC by Nazeh

Easy to do in app-land, but might be worth maintaining here for future internal changes.

2022-09-02 08:43 UTC, andrewosh commented
Cool idea @Nazeh. Definitely want something like this, but any reason you prefer the static method vs. something like `store.session({ primaryKey })`, which `namespace` then calls internally (like you're doing with `from`)?

2022-09-02 09:29 UTC, Nazeh commented
Honestly no, I was just most recently working on Protomux, so that was my bias I guess 😄 

I will push a change with in a minute

2022-09-03 08:20 UTC, andrewosh requested changes
Looks mostly good! Added a few nit typo comments and one point of confusion from the test.

2022-09-03 08:20 UTC, andrewosh commented on README.md
> +#### `const storeB = stroeA.session(opts)`
Typo "stroeA"

2022-09-03 08:20 UTC, andrewosh commented on README.md
> +Create a new Corestore that shares resources with the original, like cache, cores, replication streams, and storage, while reseting the namespace, and optionally overriding `primaryKey`.
reseting -> resetting

2022-09-03 08:20 UTC, andrewosh commented on test/all.js
> +  const session1 = store1.namespace('a').session()
Hmm, this line highlights a potential issue. It's reasonable to expect that calling `session` on a namespaced corestore returns a session with the same namespace by default, which would mean passing `namespace: this._namespace` as a constructor opt.

2022-09-05 10:51 UTC, Nazeh commented
A little problem with closing from a session if we reset the namespace, I guess there needs to be a flag like `this._isSession` if this to be merged at all! https://github.com/hypercore-protocol/corestore/blob/master/index.js#L300

2022-09-17 15:24 UTC, Nazeh commented
Updated this after the latest changes, ready for review.

2022-09-20 08:46 UTC, andrewosh approved these changes
LGTM

2022-09-20 08:47 UTC, merged

2022-09-20 08:48 UTC, andrewosh commented
Published 6.2.0